image: maven:eclipse-temurin

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean test
  artifacts:
    paths:
      - target/surefire-reports/
    reports:
      junit: target/surefire-reports/TEST-no.ntnu.idatt1002.demo.repo.MyEntityRepoTest.xml
      coverage_report:
        coverage_format: cobertura
        path: target/jacoco/coverage-reports/jacoco.xml

package:
  stage: package
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/idatt2002demo-1.0-SNAPSHOT-jar-with-dependencies.jar

generatepdf:
  image: ubuntu:20.04
  stage: package
  script:
    - apt-get update
    - apt-get install -y wget
    - apt-get install -y fontconfig libfreetype6 libjpeg-turbo8 libpng16-16 libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi xfonts-base  # installerer en bunsj med libs vi trenger for konverteringen til PDF
    - wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb  # Henter HTML-til-PDF-konverterer fra git. Vi bruker denne spesifikke pakken fordi vi vet at den fungerer i miljøet vi kjører i
    - dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
    - apt-get -y install nodejs
    - apt-get -y install npm
    - npm install -g github-wikito-converter
    - apt-get -y install git
    - export my_url="${CI_PROJECT_URL:8}"
    - export final_url="https://gitlab-ci-token:$CI_JOB_TOKEN@$my_url"
    - git clone "$final_url.wiki.git"
    - gwtc $CI_PROJECT_NAME.wiki
    - wkhtmltopdf documentation.html wiki.pdf
  artifacts:
    paths:
     - wiki.pdf
  only: 
    - web

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r javadoc/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

